/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : CCRX_blinky.c
*  Description  : Main Program
*  Creation Date: 2025-08-18
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

volatile uint32_t blinkDelay = 500; // Initial blink delay of 0.5 second (on + off is 1Hz)

void main(void);

void main(void)
{
    /* Start SW Interrupt */
    R_Config_ICU_IRQ4_Start();

    /* use count to toggle alternatively 2 LEDs */
    uint32_t count = 0;

    /* WAIT_LOOP */
    while (1) {

        count++;

        /* Write to the first LED pin */
        PIN_WRITE(LED0) = ~PIN_READ(LED0);

        if ((count % 2) == 0) {
            /* Write to the second LED pin */
            PIN_WRITE(LED1) = ~PIN_READ(LED1);
        }

        /* Delay blinkDelay milliseconds before returning */
        R_BSP_SoftwareDelay(blinkDelay, BSP_DELAY_MILLISECS);
    }
}