/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_GPIO.c
*  Description  : Main Program
*  Creation Date: 2025-08-19
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "r_smc_entry.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

void led_toggle(void) {
	PIN_WRITE(LED1) = ~PIN_READ(LED1);
}

void blink_task(void *pvParameters) {
    while(1) {
        led_toggle();
        vTaskDelay(pdMS_TO_TICKS(250));
    }
}

void main_task(void *pvParameters)
{

    /* Create all other application tasks here */
	xTaskCreate(blink_task, "Blink", configMINIMAL_STACK_SIZE, NULL, 1, NULL);
	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
