/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_Queue.c
*  Description  : Main Program
*  Creation Date: 2025-08-22
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "r_smc_entry.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

QueueHandle_t xQueue;
uint8_t data_to_send = 0;
uint8_t buf;

void vSenderTask(void *pv){
	while(1){
		xQueueSend(xQueue, &data_to_send, portMAX_DELAY);
		data_to_send++;
		vTaskDelay(pdMS_TO_TICKS(200));
	}
}

void vReceiverTask(void *pv){
	while(1){
		xQueueReceive(xQueue, &buf, 0);
		vTaskDelay(pdMS_TO_TICKS(200));
	}
}


void main_task(void *pvParameters)
{

    /* Create all other application tasks here */
	xQueue = xQueueCreate(1, sizeof(uint8_t));
	xTaskCreate(vSenderTask, "SENDER_TASK", 256, NULL, 1, NULL);
	xTaskCreate(vReceiverTask, "RECEIVER_TASK", 256, NULL, 2, NULL);
	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
