/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_Timer.c
*  Description  : Main Program
*  Creation Date: 2025-08-26
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
#include "r_smc_entry.h"
#include "Pin.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

void led_toggle(){
	PIN_WRITE(LED0) = ~PIN_READ(LED0);
}

void led_timer_callback(TimerHandle_t xTimer){
	led_toggle();
}

void main_task(void *pvParameters)
{

    /* Create all other application tasks here */
	TimerHandle_t  xLedTimer = xTimerCreate("LED_Timer", pdMS_TO_TICKS(500), pdTRUE, NULL, led_timer_callback);

	if(xLedTimer != NULL){
		xTimerStart(xLedTimer, 0);
	}

	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
