/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_EventGroup.c
*  Description  : Main Program
*  Creation Date: 2025-08-20
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "r_smc_entry.h"
#include "event_groups.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

volatile int data = 0;

EventGroupHandle_t xEventGroup;

volatile int ConsumerExecutionFlag, ProducerExecutionFlag

#define BIT_0 (1UL << 0UL)
#define BIT_1 (1UL << 1UL)

void vEventConsumerTask(void *pv){
	while(1){
		xEventGroupWaitBits(xEventGroup, BIT_0 | BIT_1, pdTRUE, pdTRUE, portMAX_DELAY);
		data++;
	}

}

void vEventProducerTask_2(void *pv){
	while(1) {
		xEventGroupSetBits(xEventGroup, BIT_1);
		vTaskDelay(pdMS_TO_TICKS(100));
	}
}

void vEventProducerTask_1(void *pv){
	while(1) {
		xEventGroupSetBits(xEventGroup, BIT_0);
		vTaskDelay(pdMS_TO_TICKS(150));
	}
}

void main_task(void *pvParameters)
{

    /* Create all other application tasks here */
	xEventGroup = xEventGroupCreate();
	xTaskCreate(vEventConsumerTask, "Consumer", 256, NULL, 1, NULL);
	xTaskCreate(vEventProducerTask_1, "Producer1", 256, NULL, 1, NULL);
	xTaskCreate(vEventProducerTask_2, "Producer2", 256, NULL, 1, NULL);
	/* Producerタスクの生成 */
	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
