/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_UART_Queue.c
*  Description  : Main Program
*  Creation Date: 2025-08-25
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include <stdio.h>              // For sprintf
#include <stdlib.h>
#include <string.h>
#include "platform.h"           // Located in the FIT BSP module
#include "r_sci_rx_if.h"        // The SCI module API interface file.
#include "r_byteq_if.h"         // The BYTEQ module API interface file.
#include "r_sci_rx_config.h"    // User configurable options for the SCI module
#include "r_sci_rx_pinset.h"
#include "r_smc_entry.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

sci_cfg_t   my_sci_config;
sci_err_t   my_sci_err;
uint8_t     my_char;
uint8_t command_buffer[32] = {0};
size_t buffer_len = 0;

QueueHandle_t msg_queue;

void my_sci_callback(void *pArgs);
static sci_hdl_t   g_my_sci_handle;

void blinker_task(void *pv){
	uint8_t recv_char[4] = {0};
	uint8_t recv_int = 100;
	while(1){
		if(xQueueReceive(msg_queue, (void *) &recv_char, 0) == pdTRUE){
			recv_int = atoi(recv_char);
		}
		PIN_WRITE(LED0) = ~PIN_READ(LED0);
		vTaskDelay(recv_int);
	}
}

void receiver_task(void *pv){
	while(1){
		/*if (R_SCI_Receive(g_my_sci_handle, &received_char, 1) == SCI_SUCCESS) {
			xQueueSend(command_queue, &received_char, portMAX_DELAY);
		}*/
		do
		{
			my_sci_err = R_SCI_Receive(g_my_sci_handle, &my_char, 1);
		} while (SCI_ERR_INSUFFICIENT_DATA == my_sci_err);

		buffer_len = strlen((char *) command_buffer);
		command_buffer[buffer_len] = my_char;
	}
}

void main_task(void *pvParameters)
{
	my_sci_config.async.baud_rate    = 115200;
	my_sci_config.async.clk_src      = SCI_CLK_INT;
	my_sci_config.async.data_size    = SCI_DATA_8BIT;
	my_sci_config.async.parity_en    = SCI_PARITY_OFF;
	my_sci_config.async.parity_type  = SCI_EVEN_PARITY;
	my_sci_config.async.stop_bits    = SCI_STOPBITS_1;
	my_sci_config.async.int_priority = 3;    // 1=lowest, 15=highest

	my_sci_err = R_SCI_Open(SCI_CH1, SCI_MODE_ASYNC, &my_sci_config, my_sci_callback, &g_my_sci_handle);

	    /* If there were an error this would demonstrate error detection of API calls. */
	if (SCI_SUCCESS != my_sci_err)
	{
		R_BSP_NOP(); // Your error handling code would go here.
	}

	R_SCI_PinSet_SCI1();
    /* Create all other application tasks here */
	xTaskCreate(blinker_task, " Task", configMINIMAL_STACK_SIZE, NULL, tskIDLE_PRIORITY + 1, NULL);
	xTaskCreate(receiver_task, "Receiver Task", 192, NULL, tskIDLE_PRIORITY + 1, NULL);
	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}


void my_sci_callback(void *pArgs)
{

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
