/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : CCRX_PWM.c
*  Description  : Main Program
*  Creation Date: 2025-08-26
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

void main(void);

void main(void)
{
	R_Config_MTU0_Start();

	while (1)
	{
		/* ---- Main Loop ---- */
	}
}
