/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_blink.c
*  Description  : Main Program
*  Creation Date: 2025-08-18
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "r_smc_entry.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

void vTask1(void *pvParameters) {
	while(1) {
		PIN_WRITE(LED0) = ~PIN_READ(LED0);
		vTaskDelay(pdMS_TO_TICKS(100));
	}
}

void vTask2(void *pvParameters) {
	while(1) {
		PIN_WRITE(LED1) = ~PIN_READ(LED1);
		vTaskDelay(pdMS_TO_TICKS(150)); }
}

void main_task(void *pvParameters)
{

    /* Create all other application tasks here */
	xTaskCreate(vTask1, "Task_1", configMINIMAL_STACK_SIZE, NULL, tskIDLE_PRIORITY + 1, NULL);
	xTaskCreate(vTask2, "Task_2", configMINIMAL_STACK_SIZE, NULL, tskIDLE_PRIORITY + 2, NULL);
	vTaskStartScheduler();

    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
