/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_Interrupt.c
*  Description  : Main Program
*  Creation Date: 2025-08-22
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "r_smc_entry.h"
#include "semphr.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

SemaphoreHandle_t xInterruptSemaphore;

void ex_gpio_irq_handler(void) {
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    xSemaphoreGiveFromISR(xInterruptSemaphore, &xHigherPriorityTaskWoken);
    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}

void vInterruptMonitorTask(void *pv) {
    while(1) {
        if (xSemaphoreTake(xInterruptSemaphore, portMAX_DELAY) == pdTRUE) {
            // 割り込み後の処理
        }
    }
}

void main_task(void *pvParameters)
{

    /* Create all other application tasks here */
	xInterruptSemaphore = xSemaphoreCreateBinary();
	xTaskCreate(vInterruptMonitorTask, "IntMonitor", 256, NULL, 2, NULL);
	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
