/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_IRQ.c
*  Description  : Main Program
*  Creation Date: 2025-08-25
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "r_smc_entry.h"
#include "r_irq_rx_if.h"
#include "r_irq_rx_config.h"
#include "Pin.h"
#include "semphr.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

static void my_irq4_callback(void *pdata);
static irq_handle_t  my_irq4_handle;

SemaphoreHandle_t xInterruptSemaphore;
void vInterruptMonitorTask(void *pv);

void main_task(void *pvParameters)
{
	irq_err_t   my_error_code;

	R_ICU_PinSet();

	my_error_code = R_IRQ_Open (IRQ_NUM_4, IRQ_TRIG_FALLING, IRQ_PRI_3, &my_irq4_handle, my_irq4_callback);
	if (IRQ_SUCCESS != my_error_code)
	{
		R_BSP_NOP();  //Handle your error here.
	}
    /* Create all other application tasks here */
	xInterruptSemaphore = xSemaphoreCreateBinary();
	xTaskCreate(vInterruptMonitorTask, "IntMonitor", 256, NULL, 2, NULL);
	vTaskStartScheduler();
    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

void vInterruptMonitorTask(void *pv) {
    while(1) {
        if (xSemaphoreTake(xInterruptSemaphore, portMAX_DELAY) == pdTRUE) {
            // 割り込み後の処理
        	PIN_WRITE(LED0) = ~PIN_READ(LED0);
        }
    }
}

static void my_irq4_callback(void *pdata){
	irq_err_t 		my_error_code;
	irq_number_t 	my_irq_number;
	uint8_t level;
	my_irq_number = *((irq_number_t *)pdata);
	BaseType_t xHigherPriorityTaskWoken = pdFALSE;

	if (IRQ_NUM_4 == my_irq_number)
	{
		/* Read the current level of the pin assigned to the specified IRQ. If it is low
		 * then a falling edge has occurred.  If high then a rising edge has occurred.      */
		my_error_code = R_IRQ_ReadInput(my_irq4_handle, &level);
		if (IRQ_SUCCESS != my_error_code)
		{
			R_BSP_NOP();  //Handle your error here.
		}
		xSemaphoreGiveFromISR(xInterruptSemaphore, &xHigherPriorityTaskWoken);
		portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
//		else if (0 == level)
//		{
//			PIN_WRITE(LED0) = 1;  // Falling edge was detected so turn LED3 on.
//
//			/* Change trigger mode to rising edge. */
//			my_trig_mode = IRQ_TRIG_RISING;
//			my_error_code = R_IRQ_Control(my_irq4_handle, IRQ_CMD_SET_TRIG, &my_trig_mode);
//			if (IRQ_SUCCESS != my_error_code)
//			{
//				R_BSP_NOP();  //Handle your error here.
//			}
//		}
//		else
//		{
//			PIN_WRITE(LED0) = 0;  //Rising edge was detected so turn LED3 off.
//
//			/* Change trigger mode to falling edge. */
//			my_trig_mode = IRQ_TRIG_FALLING;
//			my_error_code = R_IRQ_Control(my_irq4_handle, IRQ_CMD_SET_TRIG, &my_trig_mode);
//			if (IRQ_SUCCESS != my_error_code)
//			{
//				R_BSP_NOP();  //Handle your error here.
//			}
//		}
	}
}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
