/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : FreeRTOS_Semaphore.c
*  Description  : Main Program
*  Creation Date: 2025-08-20
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "r_smc_entry.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

void main_task(void *pvParameters)
{

    /* Create all other application tasks here */

    /* WAIT_LOOP */
    while(1) {
        vTaskDelay(10000);
    }

    vTaskDelete(NULL);

}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif